### ISSUE TITLE
Hyperledger Quilt migration

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/java-ilp-core#104]
In case you missed it, **Hyperledger** have created a new project called **Quilt** which will be the new home for the Java implementation of ILP: https://www.hyperledger.org/blog/2017/10/16/hyperledger-gets-cozy-with-quilt

Over the coming few days we should establish a plan for migration of our code over to a new GitHub repo(s) within the Hyperledger org.

I propose that we start by setting up a new multi-project Maven repo under hyperledger/quilt and then migrate the java projects into sub-modules.

I also propose that we try to merge outstanding PRs and make some tagged releases before we do the migration.

Lastly, do we want to preserve the flow of using `development` and `master` branches?

## Setup

- [x] Create new project in Quilt
- [x] Create new issue tags for sub-modules

## java-ilp-core

- [x] Merge outstanding PRs and trim branches to `master` and `development`
- [x] Tag and release latest code
- [x] Migrate code to `hyperledger/quilt/core`
- [x] Migrate issues to `hyperledger/quilt/` and tag as `Core`
- [x] Migrate docs/wiki to `hyperledger/quilt/docs`
- [x] Update README

## java-crypto-conditions

- [x] Merge outstanding PRs and trim branches to `master` and `development`
- [x] Tag and release latest code
- [x] Migrate code to `hyperledger/quilt/crypto-conditions`
- [x] Migrate issues to `hyperledger/quilt/` and tag as `Crypto Conditions`
- [x] Migrate docs/wiki to `hyperledger/quilt/docs`
- [x] Update rfcs/crypto-conditions to link to new code
- [x] Update README

## java-ilp-plugin

- [ ] Merge outstanding PRs and trim branches to `master` and `development`
- [ ] Tag and release latest code
- [ ] Migrate code to `hyperledger/quilt/plugin-interface`
- [ ] Migrate issues to `hyperledger/quilt/` and tag as `Ledger Plugin Interface`
- [ ] Migrate docs/wiki to `hyperledger/quilt/docs`

## java-ilp-connector

- [ ] Merge outstanding PRs and trim branches to `master` and `development`
- [ ] Tag and release latest code
- [ ] Migrate code to `hyperledger/quilt/connector`
- [ ] Migrate issues to `hyperledger/quilt/` and tag as `Connector`
- [ ] Migrate docs/wiki to `hyperledger/quilt/docs`

**Comment by sappenin** [comment]
How do we go about getting the project setup at Hyperledger?

**Comment by adrianhopebailie** [comment]
I'm co-ordinating that with the Linux Foundation

**Comment by adrianhopebailie** [comment]
@sappenin What do you think about migrating `java-ilp-connector` and and `java-ilp-plugin`?

Can I close this issue and we can track that in those repos?

**Comment by sappenin** [comment]
@adrianhopebailie Sounds good to me!
