### ISSUE TITLE
Discuss ILP Packet Design and Implementation

### ISSUE THREAD

**Issue by sappenin** [interledger/java-ilp-core#17]
See [RFC Issue 146](https://github.com/interledger/rfcs/issues/146) for discussion, and the proposed [Interledger Protocol data format](https://gist.github.com/justmoon/a59fd43958ce421c8b4a88d5143c718b) and discuss how any of this should be implemented in Java.

**Comment by adrianhopebailie** [comment]
We definitely need to implement concrete classes for all the packet formats that are being proposed here: https://github.com/interledger/rfcs/pull/168

**Comment by sappenin** [comment]
@adrianhopebailie I've started looking at [interledger/rfcs#168](https://github.com/interledger/rfcs/pull/168), and it looks like the conditional payment stuff has been removed in that PR.  Is the idea that a condition/expiry info for a non-optimisitic-mode payment will be some sort of "custom header" stuffed into the `InterledgerProtocolPaymentMessage.data` field?

**Comment by sappenin** [comment]
FYI - I have a provisional interface defined for the InterledgerPacket interface - I'll try to commit tonight or tomorrow for feedback.  It's not clear to me if the PaymentPacket and the ILQPPacket and the CCP packets should be distinct "things", or if they should all inherit from a common interface.

**Comment by adrianhopebailie** [comment]
Awesome!

>It's not clear to me if the PaymentPacket and the ILQPPacket and the CCP packets should be distinct "things", or if they should all inherit from a common interface.

They are all distinct packets

**Comment by sappenin** [comment]
I've created an initial PR for this via [PR #24](https://github.com/interledger/java-ilp-core/pull/24).  The packets are distinct classes, but they have some overlapping qualities, so they inherit from the same super-type.  Please review and provide recommendations if anyone prefers a different style or design.

**Comment by sappenin** [comment]
Closing this issue in deference to [PR #28](https://github.com/interledger/java-ilp-core/pull/28).  Please make comments in there, or open a new issue if there are concerns.
