### ISSUE TITLE
Decide where to put usage/readme info

### ISSUE THREAD

**Issue by sappenin** [interledger/java-ilp-core#33]
We need to decide where to put README and otherwise useful information for developer consmption.  

One nice example of a Github wiki is the [Netflix Hystrix](https://github.com/Netflix/Hystrix/wiki) project, where they have light README files and then put most information in the github wiki.  Specifically, [this wiki page](https://github.com/Netflix/Hystrix/wiki/How-To-Use) is very useful when trying to use the library in implementations.

**Comment by sappenin** [comment]
On the previous ILP Java call, we discussed putting documentation for the project into the /docs folder of the project, which would allow publishing to Github pages.  See the [scripts](https://github.com/interledger/rfcs/tree/master/scripts) folder in the RFCs project.

**Comment by adrianhopebailie** [comment]
> Overall, unlike the RFCs project, it's not clear to me what this buys us over just writing our README/Examples/Usages documentation in the Github wiki. The wiki is editable directly inside of the github website (in a browser), and is also versioned. I suppose the only thing missing would be CSS styling? But the downside is reading the doco for this project would take the user away from the actual Github project, which is a slight disadvantage IMHO.

The other advantage is control over edits. Edits would have to be made by PRs. The markdown files would also be published to the web, just need to test how that would work.

**Comment by sappenin** [comment]
> The markdown files would also be published to the web, just need to test how that would work.

Sounds good - where do we store the markdown files?  Maybe in `/docsource`?

**Comment by sappenin** [comment]
I added a wiki-page (for now) to outline the Codec Framework because it wasn't clear where we should put the markdown for the Github Pages stuff.  Once that's worked out, however, we can transition away from the wiki (and turn it off).  

See here: https://github.com/interledger/java-ilp-core/wiki/InterledgerPacket-Handling-Framework

**Comment by sappenin** [comment]
Closing this for now - I think once https://github.com/interledger/java-crypto-conditions/issues/48 is resolved for Javadoc, we'll have a better idea if it makes sense to push usage/README into a Github Pages site for this project (java-ilp-core) and that one (java-crypto-conditions).
