### ISSUE TITLE
Cleanup Checkstyle errors

### ISSUE THREAD

**Issue by sappenin** [interledger/java-ilp-core#34]
We need to go through the code and make sure there are no Checkstyle errors so that the build is cleaner.  This information can be seen currently as warnings after executing `gradle build test`.

**Comment by andrew-g-za** [comment]
hehehe i hate to be that guy but checkstyle was passing for me (on the psk and oer-fixes branch). I'm a few commits behind on the dev branch, let me work through it to try figure out whats going on.

If you know of a way to make checkstyle output more visible from circle-ci, shout!

**Comment by andrew-g-za** [comment]
The good news:
looks like we can get circle-ci to correctly fail the build if checkstyle fails (thanks to Adrians superior google-fu) - see #39 

The bad news:
the checkstyle tests passed at [build 40](https://circleci.com/gh/interledger/java-ilp-core/40) which is for commit 66d2681. They start failing at build 41, which is for your commit 235d3df :D
(the checkstyle report is kept as an artifact).
 
If i find some time i'll try clean it up, might only be end of next week though.

**Comment by sappenin** [comment]
Oh interesting - I thought checkstyle was set to only warn on the build, not fail.  I can look at this too.

**Comment by adrianhopebailie** [comment]
We changed it to fail on a warning otherwise CircleCI passes the build even if there are CheckStyle issues.
