### ISSUE TITLE
Drop the InterledgerPacket interface

### ISSUE THREAD

**Issue by sappenin** [interledger/java-ilp-core#36]
Per the Java ILP call and PR #28, we are going to drop the InterledgerPacket interface so there's a clear separation between the Java domain model and any encoding structures.  Essentially, the codec should be the one to know if a "type" bit should be present or not for codec purposes.

**Comment by sappenin** [comment]
After looking at this more closely, I think we need to keep the concept of an `InterledgerPacket` for a couple of reasons:

1. InterledgerPacket isn't just a concept that exists inside of the coder/decoder machinery.  Instead, it's a concept that exists outside of this layer, too.  Specifically, it's a representation of something that can be sent from one node to another in an Interledger transaction.  I like to think of it as the highest-level object that Interledger uses.  Examples of a "packet" include `InterledgerPayment`, ILQP quote request/response objects, possibly PSK objects, etc.  Conversely, something like an `InterledgerAddress` is _not_ a packet, even though it is used inside of nearly every class that inherits from `InterledgerPacket`("having" and "being" are two different concepts).

1. Additionally, during the codec process, it will be useful to allow developers to provide business logic to react to a decoded Interledger objects in cases where the actual decoded type isn't known at compile time.  To accomplish this, developers can construct instances of `InterledgerPacket.Handler.AbstractHandler`, and will be prompted by the IDE to handle each potential instance of `InterledgerPacket` by supplying business-logic for each case at compile-time.  Then, at runtime, the Handler will pick an appropriate business-logic method based upon the actual runtime version encountered.

I will add some documentation and examples surrounding the second point shortly, just for clarity.

All that to say, I think it's important from a design perspective to maintain the concept of a "packet" in our non-codec layers: It helps inside the codecs, but also helps outside the codec layers as well.

Thoughts?

**Comment by adrianhopebailie** [comment]
This makes a lot of sense. Interested to see the code to clarify.
