### ISSUE TITLE
ILQP current vs future implementation

### ISSUE THREAD

**Issue by andrew-g-za** [interledger/java-ilp-core#42]
Hi,

I started updating java-ilp-client to be compatible with the changes made in java-ilp-core.

I bumbled around for a while trying to understand why ILQP had changed so much until I stumbled on the [InterledgerQuotingProtocol ASN](https://github.com/interledger/rfcs/blob/96647328557ec794d44d68f58becbdeb3b09c2db/asn1/InterledgerQuotingProtocol.asn)

Unfortunately though, the [ILQP RFC](https://github.com/interledger/rfcs/blob/master/0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md) has this snippet right at the end (emphasis mine)

> The InterledgerQuotingProtocol.asn ASN.1 module _tentatively_ describes the binary messages for a _future_ version of ILQP. **This is not final and is not yet deployed at the time of writing**.

That leaves the current definition in java-ilp-core incompatible with whats currently published (at least, from what I gather, maybe the RFC docs are out of date).

Its madness to throw out your good work on the new standard, so **if** we need to support the current version, how about we move what you have done into a 'future' package `org.interledger.future.ilqp`
and put something compatible with the 'current' spec in `org.interledger.ilqp`?

 @adrianhopebailie - could you please confirm the status of ILQP - is it worth going back, or not?

**Comment by sappenin** [comment]
I'm pretty sure the ASN.1 spec is authoritative, and the RFC doc is just outdated.  For example, see https://github.com/interledger/rfcs/pull/218/files.  

Unless there's some use-case I'm not aware of that needs to be using the old ILQP code, my vote would be to just "roll forward" and work off the ASN1 definitions.

**Comment by adrianhopebailie** [comment]
Looking at the current state of the JS implementation I think we should probably just move to the binary messages. I don't expect us to interface directly with the JS implementations at that level soon and by the time we do they'll be using the binary protocol

**Comment by andrew-g-za** [comment]
OK fair enough. I'll continue efforts using the new message scheme. I'll propose some new API changes in ilp-core, since they existing one doesnt fit the new scheme easily.
