### ISSUE TITLE
Switch to BigInteger from long

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/java-ilp-core#57]
We are still using a long in many places for amounts. These are encoded as UInt64 which is too big for a long so there is a risk that we'll break things.

Need to switch to BigInteger and stop using deprecated functions on the UInt64 codecs.

**NOTE**: Need to ensure that we encode and decode accurately as the default byte encoding of BigInteger includes a sign bit. We only want unsigned 64 bit integers.

**Comment by andrew-g-za** [comment]
+1

The OerUint64 codec already has this, so its just a matter of updating all the models to use BigInteger instead of long.
