### ISSUE TITLE
java ilp  core not running

### ISSUE THREAD

**Issue by THEViveKL** [interledger/java-ilp-core#60]
![image](https://user-images.githubusercontent.com/30408710/28556253-a4f4986a-7122-11e7-8539-1ace27529576.png)

Trying to run this program but not able to run it although build is successful.
Please help me.

![image](https://user-images.githubusercontent.com/30408710/28556261-b44b60be-7122-11e7-80b4-c654eb1e5380.png)
Also done to import project as gradle project then getting above error (Using eclipse).

**Comment by andrew-g-za** [comment]
Hi,

Its a bit hard to tell from the screenshots, but i think you need to clone the java-crypto-conditions project too. We are busy migrating the dependencies to external jars, but until then you need to have both projects in a root folder. 

From the readme

> > This project depends on Java Crypto-Conditions. To contribute to this library, clone the following two projects to the same folder (the dependency crypto-conditions is not available as a package yet so we use a project dependency).
> 
> $ git clone https://github.com/interledger/java-crypto-conditions.git
> $ git clone https://github.com/interledger/java-ilp-core.git

So for example make a folder `C:\projects\ilp` ,then 

```bash
$ C:\
$ cd projects\ilp
$ git clone https://github.com/interledger/java-crypto-conditions.git
$ git clone https://github.com/interledger/java-ilp-core.git
$ cd java-ilp-core
$ gradle build
```

That should get the build to work, but i suggest switching to the development branches of both java-crypto-conditions and java-ilp-core.

As for the eclipse issue - i haven't seen that one before. What version of eclipse are you using? What gradle plugin are you using? (I've been using eclipse neon3 (4.6.3) with eclipse buildship 2.0.2.)

**Comment by THEViveKL** [comment]
hi,

I have tried your solution.
When i use command gradle build in ilp-core it shows message that build successful.
But when i tried to run this it shows build failed.

Also for successful build i have to remove test folder from project as some tests are failed (to be precise 3 tests are failed).

I just want to see output as i want to learn about interledger and make solution in .net.

Is there anything i can do to run this program.

Thank you for your help.

**Comment by andrew-g-za** [comment]
Hi,

Perhaps we are misunderstanding each other. The java-ilp-core and java-crypto-conditions libraries are not applications themselves - they are simply libraries that provide ILP functionality _to be used by_ applications. For example, take a look at [java-ilp-client-spring-boot](https://github.com/interledger/java-ilp-client-spring-boot), which is a command line program that will connect to a ledger (although I think it is somewhat out of date as some of the underlying specs have changed since it was last worked on).

**Comment by THEViveKL** [comment]
Hi,

Yeah I misunderstood this lib, thank you for link 
[ java-ilp-client-spring-boot,](https://github.com/interledger/java-ilp-client-spring-boot)

I will definitely look into this.
Thank you for your help.

**Comment by adrianhopebailie** [comment]
@THEViveKL sorry for coming late to this.

A few things:

1. As @andrew-g-za points out java-ilp-core is just a library. It provides the core models and codecs for the protocol. It's coming close to a stable release which we'll tag and put into Maven central soon.
2. There are a few other Java based projects at varying levels of maturity for running ILP services such as java-ilp-client-spring-boot. They will be the next focus now that the core lib is stable.
3. If you are interested in learning more join our Gitter channel https://gitter.im/interledger/Lobby

**Comment by THEViveKL** [comment]
@adrianhopebailie
Thank you for reply i will definitely look into it.
