### ISSUE TITLE
Restrict allowed chars in headers for PSK

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/java-ilp-core#69]
See https://github.com/interledger/rfcs/pull/257 for context

**Comment by controlsurface** [comment]
@sappenin , all, am planning on taking this one on next.

**Comment by sappenin** [comment]
Sounds good - although you’ll probably want to work off the Hyperledger version now - we’re moving the project under that governance structure - https://github.com/hyperledger/quilt
