### ISSUE TITLE
Switch to using Maven only?

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/java-ilp-core#88]
We currently have an overly complex build system with both Maven and Gradle.

The majority of contributors use Maven and it has proven to be better supported by plugins. It would be helpful to switch but I propose we take a contributor vote.

**Comment by earizon** [comment]
Not problem for me to default to maven. I vote for the one that simplifies CI. (I'm not aware of the pros and cons of each one for CI)

**Comment by adrianhopebailie** [comment]
I suggest we implement this change as part of migrating the code over to the Hyperledger Quilt project

**Comment by rizwantanoli** [comment]
I am not a contributor yet, hope to become one, but my preference would be Maven
